### PR TITLE
Added support for component dependencies

### PR DESCRIPTION
**Pull request by jvanderwee**
Added support for components which have other components as dependencies.

### CODE REVIEW

**Comment by fabioCollini** [comment]
Thanks for the pull request!
Just a question, in this way can you override an object defined in the second component?
Another solution can be to do it inside the rule, just pass the module of all the components and the rule set the module to the right component?

**Comment by fabioCollini** [comment]
Or something like:

    addComponentDependency(MyComponent2.class, new MyModule2())

In this way the secondo component is constructed in the same way of the main component (so the objects can be overridden)

**Comment by jvanderwee** [comment]
Good thinking, will have a go at this later. Thanks!

**Comment by jvanderwee** [comment]
Cool I've made these changes, let me know what you think!

**Comment by fabioCollini** [comment]
Great! Thanks a lot!

**Pull request merged**
