### PR TITLE
Update dagger version to 2.1

### PR DESCRIPTION
**Pull request by nspeeD**
- Added new version of dagger 2.1

### CODE REVIEW

**Comment by jvanderwee** [comment]
Has Dagger 2.1 been released?

**Comment by nspeeD** [comment]
2.1 available in maven (9 March) -> http://mvnrepository.com/artifact/com.google.dagger/dagger/2.1 but in the github page is marked as SNAPSHOT.

**Comment by fabioCollini** [comment]
Is there any documentation available about Dagger 2.1? Is it compatible with Dagger 2?
I am not sure whether DaggerMock should be compiled using the last version of Dagger. I know that in both cases you can override Dagger version in build.gradle but maybe compiling using Dagger 2.1 can be a problem in some projects.

**Comment by fabioCollini** [comment]
I changed the definition of the dependency, now dagger is defined as provided to avoid conflicts if the app uses Dagger 2.1 or 2.2.

**Pull request closed without merging**
