### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by yairkukielka**
I have seen a some people that are interested in this great library, but it looks like they don't know what it does and how it can be used. I tried to improve a bit the documentation so it's easier to understand.

### CODE REVIEW

**Comment by fabioCollini** [comment]
Thanks a lot!
I am writing a medium post about DaggerMock, I'll publish it in a few days. if you want to take a look at it it will be great, it's available here: https://medium.com/@fabioCollini/c8487ed01b56
Any feedback is welcome!

**Comment by yairkukielka** [comment]
I just read it, and I think it's good! If I had to add anything, it would be to create an index of the different sections for showing different testing strategies, just as you did in your github examples. Something like this would greatly simplify concepts for the reader:

A) Instrumentation/funcional tests (androidTest folder using ActivityTestRule)
1 - Espresso tests with TestComponent
2 - Instrumentation tests with DaggerMockRule
3 - Instrumentation tests with a custom dagger rule

B) Unit tests (test folder)
1 - Robolectric tests
2 - Mockito rule with TestComponent
3 - Hybrid of Mockito & DaggerMock
4 - DaggerMock

**Comment by fabioCollini** [comment]
Thanks for the suggestions! I added some title to simplify the structure of the post. It's available on medium here: https://medium.com/@fabioCollini/android-testing-using-dagger-2-mockito-and-a-custom-junit-rule-c8487ed01b56

**Comment by yairkukielka** [comment]
Looks great!

**Pull request merged**
